'use client'

import React, { createContext, useContext, useState, ReactNode } from 'react'

export type Language = 'en' | 'km' | 'zh' | 'ja' | 'ko' | 'hi' | 'ar' | 'fr' | 'es' | 'pt' | 'id' | 'th'

export const languageNames: Record<Language, string> = {
  en: '🇺🇸 English',
  km: '🇰🇭 ខ្មែរ',
  zh: '🇨🇳 中文',
  ja: '🇯🇵 日本語',
  ko: '🇰🇷 한국어',
  hi: '🇮🇳 हिन्दी',
  ar: '🇸🇦 العربية',
  fr: '🇫🇷 Français',
  es: '🇪🇸 Español',
  pt: '🇧🇷 Português',
  id: '🇮🇩 Indonesia',
  th: '🇹🇭 ภาษาไทย',
}

type Translations = { [key in Language]: Record<string, string> }

const translations: Translations = {
  en: {
    'app.title': 'BabyCare',
    'app.subtitle': 'Welcome to your care journey 🌸',
    'app.welcome.big': 'Care that Comes to You.',
    'app.welcome.sub': 'Experience professional prenatal checkups in the comfort and safety of your own home.',
    'role.parent': 'Parent',
    'role.doctor': 'Doctor',
    'nav.dashboard': 'Dashboard',
    'nav.documents': 'Documents',
    'nav.chatbot': 'AI Chatbot',
    'nav.records': 'Medical Records',
    'nav.patients': 'Patients',
    'nav.booking': 'Book Doctor',
    'nav.clinics': 'Find Clinics',
    'nav.profile': 'Profile',
    'nav.risk': 'Risk Prediction',
    'nav.schedule': 'Schedule',
    'nav.chat': 'Chat',
    'nav.earnings': 'Earnings',
    'nav.subscription': 'Subscription',
  },
  km: {
    'app.title': 'BabyCare',
    'app.subtitle': 'សូមស្វាគមន៍មកកាន់ដំណើរថែទាំរបស់អ្នក 🌸',
    'app.welcome.big': 'ជីវិតថ្មីគ្រប់ទំហំ គឺជាអព្ភូតហេតុ។',
    'app.welcome.sub': 'យើងនៅទីនេះដើម្បីដើរជាមួយអ្នករហូត។',
    'role.parent': 'ឪពុកម្តាយ',
    'role.doctor': 'វេជ្ជបណ្ឌិត',
    'nav.dashboard': 'ផ្ទាំងគ្រប់គ្រង',
    'nav.documents': 'ឯកសារ',
    'nav.chatbot': 'AI ជជែក',
    'nav.records': 'កំណត់ត្រាវេជ្ជសាស្ត្រ',
    'nav.booking': 'កក់វេជ្ជបណ្ឌិត',
    'nav.clinics': 'ស្វែងរកគ្លីនិក',
    'nav.profile': 'ប្រវត្តិរូប',
    'nav.risk': 'ការព្យាករណ៍ហានិភ័យ',
    'nav.schedule': 'កាលវិភាគ',
    'nav.chat': 'ជជែក',
    'nav.earnings': 'ប្រាក់ចំណូល',
    'nav.subscription': 'ការជាវ',
  },
  zh: {
    'app.title': 'BabyCare',
    'app.subtitle': '欢迎来到您的关爱之旅 🌸',
    'app.welcome.big': '每一个新生命都是奇迹。',
    'app.welcome.sub': '我们在这里，陪伴您走过每一个美好的步骤。',
    'role.parent': '家长',
    'role.doctor': '医生',
    'nav.dashboard': '仪表板',
    'nav.documents': '文件',
    'nav.chatbot': 'AI 聊天',
    'nav.records': '医疗记录',
    'nav.booking': '预约医生',
    'nav.clinics': '查找诊所',
    'nav.profile': '个人资料',
    'nav.risk': '风险预测',
    'nav.schedule': '日程',
    'nav.chat': '聊天',
    'nav.earnings': '收益',
    'nav.subscription': '订阅',
  },
  ja: {
    'app.title': 'BabyCare',
    'app.subtitle': 'ケアの旅へようこそ 🌸',
    'app.welcome.big': 'すべての新しい命は奇跡です。',
    'app.welcome.sub': 'あなたの美しい一歩一歩を共に歩みます。',
    'role.parent': '親',
    'role.doctor': '医師',
    'nav.dashboard': 'ダッシュボード',
    'nav.documents': '書類',
    'nav.chatbot': 'AIチャット',
    'nav.records': '医療記録',
    'nav.booking': '医師を予約',
    'nav.clinics': 'クリニックを探す',
    'nav.profile': 'プロフィール',
    'nav.risk': 'リスク予測',
    'nav.schedule': 'スケジュール',
    'nav.chat': 'チャット',
    'nav.earnings': '収益',
    'nav.subscription': 'サブスクリプション',
  },
  ko: {
    'app.title': 'BabyCare',
    'app.subtitle': '케어 여정에 오신 것을 환영합니다 🌸',
    'app.welcome.big': '모든 새 생명은 기적입니다.',
    'app.welcome.sub': '아름다운 모든 걸음걸음을 함께 걷겠습니다.',
    'role.parent': '부모',
    'role.doctor': '의사',
    'nav.dashboard': '대시보드',
    'nav.documents': '문서',
    'nav.chatbot': 'AI 채팅',
    'nav.records': '의료 기록',
    'nav.booking': '의사 예약',
    'nav.clinics': '클리닉 찾기',
    'nav.profile': '프로필',
    'nav.risk': '위험 예측',
    'nav.schedule': '일정',
    'nav.chat': '채팅',
    'nav.earnings': '수익',
    'nav.subscription': '구독',
  },
  hi: {
    'app.title': 'BabyCare',
    'app.subtitle': 'आपकी देखभाल यात्रा में आपका स्वागत है 🌸',
    'app.welcome.big': 'हर नया जीवन एक चमत्कार है।',
    'app.welcome.sub': 'हम आपके हर खूबसूरत कदम पर आपके साथ हैं।',
    'role.parent': 'माता-पिता',
    'role.doctor': 'डॉक्टर',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.documents': 'दस्तावेज़',
    'nav.chatbot': 'AI चैट',
    'nav.records': 'चिकित्सा रिकॉर्ड',
    'nav.booking': 'डॉक्टर बुक करें',
    'nav.clinics': 'क्लिनिक खोजें',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.risk': 'जोखिम भविष्यवाणी',
    'nav.schedule': 'अनुसूची',
    'nav.chat': 'चैट',
    'nav.earnings': 'आय',
    'nav.subscription': 'सदस्यता',
  },
  ar: {
    'app.title': 'BabyCare',
    'app.subtitle': 'مرحباً بك في رحلة الرعاية 🌸',
    'app.welcome.big': 'كل حياة جديدة معجزة.',
    'app.welcome.sub': 'نحن هنا لنسير معك في كل خطوة جميلة.',
    'role.parent': 'والد/والدة',
    'role.doctor': 'طبيب',
    'nav.dashboard': 'لوحة التحكم',
    'nav.documents': 'وثائق',
    'nav.chatbot': 'دردشة AI',
    'nav.records': 'السجلات الطبية',
    'nav.booking': 'حجز طبيب',
    'nav.clinics': 'البحث عن عيادات',
    'nav.profile': 'الملف الشخصي',
    'nav.risk': 'توقع المخاطر',
    'nav.schedule': 'الجدول الزمني',
    'nav.chat': 'دردشة',
    'nav.earnings': 'الأرباح',
    'nav.subscription': 'الاشتراك',
  },
  fr: {
    'app.title': 'BabyCare',
    'app.subtitle': 'Bienvenue dans votre parcours de soins 🌸',
    'app.welcome.big': 'Chaque nouvelle vie est un miracle.',
    'app.welcome.sub': 'Nous sommes là pour marcher avec vous à chaque étape.',
    'role.parent': 'Parent',
    'role.doctor': 'Médecin',
    'nav.dashboard': 'Tableau de bord',
    'nav.documents': 'Documents',
    'nav.chatbot': 'Chat IA',
    'nav.records': 'Dossiers médicaux',
    'nav.booking': 'Réserver un médecin',
    'nav.clinics': 'Trouver des cliniques',
    'nav.profile': 'Profil',
    'nav.risk': 'Prédiction de risque',
    'nav.schedule': 'Planning',
    'nav.chat': 'Chat',
    'nav.earnings': 'Revenus',
    'nav.subscription': 'Abonnement',
  },
  es: {
    'app.title': 'BabyCare',
    'app.subtitle': 'Bienvenida a tu viaje de cuidado 🌸',
    'app.welcome.big': 'Cada nueva vida es un milagro.',
    'app.welcome.sub': 'Estamos aquí para caminar contigo en cada hermoso paso.',
    'role.parent': 'Padre/Madre',
    'role.doctor': 'Doctor',
    'nav.dashboard': 'Panel',
    'nav.documents': 'Documentos',
    'nav.chatbot': 'Chat IA',
    'nav.records': 'Registros médicos',
    'nav.booking': 'Reservar médico',
    'nav.clinics': 'Buscar clínicas',
    'nav.profile': 'Perfil',
    'nav.risk': 'Predicción de riesgo',
    'nav.schedule': 'Horario',
    'nav.chat': 'Chat',
    'nav.earnings': 'Ganancias',
    'nav.subscription': 'Suscripción',
  },
  pt: {
    'app.title': 'BabyCare',
    'app.subtitle': 'Bem-vinda à sua jornada de cuidados 🌸',
    'app.welcome.big': 'Cada nova vida é um milagre.',
    'app.welcome.sub': 'Estamos aqui para caminhar com você em cada belo passo.',
    'role.parent': 'Pais',
    'role.doctor': 'Médico',
    'nav.dashboard': 'Painel',
    'nav.documents': 'Documentos',
    'nav.chatbot': 'Chat IA',
    'nav.records': 'Prontuários',
    'nav.booking': 'Agendar médico',
    'nav.clinics': 'Encontrar clínicas',
    'nav.profile': 'Perfil',
    'nav.risk': 'Previsão de risco',
    'nav.schedule': 'Agenda',
    'nav.chat': 'Chat',
    'nav.earnings': 'Ganhos',
    'nav.subscription': 'Assinatura',
  },
  id: {
    'app.title': 'BabyCare',
    'app.subtitle': 'Selamat datang di perjalanan perawatan Anda 🌸',
    'app.welcome.big': 'Setiap kehidupan baru adalah keajaiban.',
    'app.welcome.sub': 'Kami di sini untuk menemani setiap langkah indah Anda.',
    'role.parent': 'Orang Tua',
    'role.doctor': 'Dokter',
    'nav.dashboard': 'Dasbor',
    'nav.documents': 'Dokumen',
    'nav.chatbot': 'Chat AI',
    'nav.records': 'Rekam Medis',
    'nav.booking': 'Pesan Dokter',
    'nav.clinics': 'Cari Klinik',
    'nav.profile': 'Profil',
    'nav.risk': 'Prediksi Risiko',
    'nav.schedule': 'Jadwal',
    'nav.chat': 'Chat',
    'nav.earnings': 'Penghasilan',
    'nav.subscription': 'Langganan',
  },
  th: {
    'app.title': 'BabyCare',
    'app.subtitle': 'ยินดีต้อนรับสู่การเดินทางดูแลของคุณ 🌸',
    'app.welcome.big': 'ทุกชีวิตใหม่คือปาฏิหาริย์',
    'app.welcome.sub': 'เราอยู่ที่นี่เพื่อก้าวเดินไปกับคุณในทุกขั้นตอนที่สวยงาม',
    'role.parent': 'ผู้ปกครอง',
    'role.doctor': 'แพทย์',
    'nav.dashboard': 'แดชบอร์ด',
    'nav.documents': 'เอกสาร',
    'nav.chatbot': 'แชท AI',
    'nav.records': 'บันทึกการแพทย์',
    'nav.booking': 'จองแพทย์',
    'nav.clinics': 'ค้นหาคลินิก',
    'nav.profile': 'โปรไฟล์',
    'nav.risk': 'พยากรณ์ความเสี่ยง',
    'nav.schedule': 'ตารางเวลา',
    'nav.chat': 'แชท',
    'nav.earnings': 'รายได้',
    'nav.subscription': 'การสมัครสมาชิก',
  },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
